In [17]:
import pandas as pd
import datetime

path=r'D:\july_1st_mandrill_export_activity\activity.csv'
df = pd.read_csv(path)
df['just_date'] = pd.to_datetime(df['Date']).dt.normalize()
df

,Date,Email Address,Sender,Subject,Status,Tags,Subaccount,Opens,Clicks,Bounce Detail,just_date
0,2021-06-09 23:45:53,hersheykiss_843@yahoo.com,news@skidos.com,Welcome to Skidos!,soft-bounced,NaN,skidos_production,0,0,"smtp;554 30 Sorry, your message to hersheykiss...",2021-06-09
1,2021-06-18 13:07:33,mariasm01@hotmail.com,news@skidos.com,¡Bienvenido/a a SKIDOS!,sent,NaN,skidos_production,0,0,NaN,2021-06-18
2,2021-06-15 16:48:03,majayoussef1996@icloud.com,news@skidos.com,[Skidos] Bitte setzen Sie ihr Passwort zurück,sent,NaN,skidos_production,0,0,NaN,2021-06-15
3,2021-06-24 22:51:37,ashleyibarra967@gmail.com,news@skidos.com,Welcome to Skidos!,sent,NaN,skidos_production,0,0,NaN,2021-06-24
4,2021-06-16 18:33:57,kellynsummer@yahoo.com,news@skidos.com,[Skidos] New password,sent,NaN,skidos_production,2,0,NaN,2021-06-16
...,...,...,...,...,...,...,...,...,...,...,...
61963,2021-06-04 08:04:58,sdk.ll@yopmail.com,news@skidos.com,[Skidos] Please reset your password,sent,NaN,skidos_production,0,0,NaN,2021-06-04
61964,2021-06-26 04:07:14,yolanda.aguilar19@outlook.com,news@skidos.com,[Skidos] New password,sent,NaN,skidos_production,0,0,NaN,2021-06-26
61965,2021-06-20 05:26:59,girumgk@yahoo.com,news@skidos.com,[Skidos] Please reset your password,sent,NaN,skidos_production,1,0,NaN,2021-06-20
61966,2021-06-22 22:59:26,phoenixmoritz313@gmail.com,news@skidos.com,[Skidos] Please reset your password,sent,NaN,skidos_production,4,1,NaN,2021-06-22
61967,2021-06-14 02:48:23,dvbhardwaj@Gmail.com,news@skidos.com,Welcome to Skidos!,sent,NaN,skidos_production,1,0,NaN,2021-06-14

In [19]:
def remove_bogus_emails(df):
    """
    Removes test emails & special emails such as the ones used by developer partners
    """
    #unwanted_emails_list =  ['testing1ajeet@gmail.com']
    #df = df.loc[df['Email'].str.contains("@")==True]
    df = df.loc[df['Email Address'].str.contains("yopmail")==False]
    df = df.loc[df['Email Address'].str.contains("ypomail")==False]
    df = df.loc[df['Email Address'].str.contains("gopmail")==False]
    df = df.loc[df['Email Address'].str.contains("skidos.com")==False]
    #df = df.loc[~df['Email Address'].isin(unwanted_emails_list)]
    return df
emails_removed_df = remove_bogus_emails(df)
print("---------------after removing bogus emails-----------------")
print(emails_removed_df.shape)


def remove_status_other_sent(df):
    """
    Removes rows with Status other than sent
    """
    status_strings =  ['soft-bounced',
                       'hard-bounced',
                       'spam','rejected',
                       'defered', 'bounced']
    df = df.loc[~df['Status'].isin(status_strings)]
    return df
filtered_df = remove_status_other_sent(emails_removed_df)
print(filtered_df.shape)
print("-----------after removing other than sent status-------------")

# def retriving_subjects(df):
#     """
#     Retrieve rows with Subject containing 'Pelase reset your password'
#     """
#     subjects_strings =  ['Please reset your password']
#     df = df.loc[df['Subject'].isin(subjects_strings)]
#     return df
# reset_pwd_df = retriving_subjects(filtered_df)
# print("--------after secting on Please reset your password-----------------")
# print(reset_pwd_df.shape)

---------------after removing bogus emails-----------------
(58100, 11)
(51510, 11)
-----------after removing other than sent status rows-------------

In [13]:
df['just_date'] = pd.to_datetime(df['Date']).dt.normalize()

In [14]:
df['just_date']

0       2021-06-09
1       2021-06-18
2       2021-06-15
3       2021-06-24
4       2021-06-16
           ...
61963   2021-06-04
61964   2021-06-26
61965   2021-06-20
61966   2021-06-22
61967   2021-06-14
Name: just_date, Length: 61968, dtype: datetime64[ns]

In [15]:
df.head()

,Date,Email Address,Sender,Subject,Status,Tags,Subaccount,Opens,Clicks,Bounce Detail,just_date
0,2021-06-09 23:45:53,hersheykiss_843@yahoo.com,news@skidos.com,Welcome to Skidos!,soft-bounced,NaN,skidos_production,0,0,"smtp;554 30 Sorry, your message to hersheykiss...",2021-06-09
1,2021-06-18 13:07:33,mariasm01@hotmail.com,news@skidos.com,¡Bienvenido/a a SKIDOS!,sent,NaN,skidos_production,0,0,NaN,2021-06-18
2,2021-06-15 16:48:03,majayoussef1996@icloud.com,news@skidos.com,[Skidos] Bitte setzen Sie ihr Passwort zurück,sent,NaN,skidos_production,0,0,NaN,2021-06-15
3,2021-06-24 22:51:37,ashleyibarra967@gmail.com,news@skidos.com,Welcome to Skidos!,sent,NaN,skidos_production,0,0,NaN,2021-06-24
4,2021-06-16 18:33:57,kellynsummer@yahoo.com,news@skidos.com,[Skidos] New password,sent,NaN,skidos_production,2,0,NaN,2021-06-16

In [16]:
def remove_bogus_emails(df):
    """
    Removes test emails & special emails such as the ones used by developer partners
    """
    #unwanted_emails_list =  ['testing1ajeet@gmail.com']
    #df = df.loc[df['Email'].str.contains("@")==True]
    df = df.loc[df['Email Address'].str.contains("yopmail")==False]
    df = df.loc[df['Email Address'].str.contains("ypomail")==False]
    df = df.loc[df['Email Address'].str.contains("gopmail")==False]
    df = df.loc[df['Email Address'].str.contains("skidos.com")==False]
    #df = df.loc[~df['Email Address'].isin(unwanted_emails_list)]
    return df
emails_removed_df = remove_bogus_emails(df)
print("---------------after removing bogus emails-----------------")
print(emails_removed_df.shape)


def remove_status_other_sent(df):
    """
    Removes rows with Status other than sent
    """
    status_strings =  ['soft-bounced',
                       'hard-bounced',
                       'spam','rejected',
                       'defered', 'bounced']
    df = df.loc[~df['Status'].isin(status_strings)]
    return df
filtered_df = remove_status_other_sent(emails_removed_df)
print(filtered_df.shape)
print("-----------after removing other than sent status rows-------------")

def retriving_subjects(df):
    """
    Retrieve rows with Subject containing 'Pelase reset your password'
    """
    subjects_strings =  ['Please reset your password']
    df = df.loc[df['Subject'].isin(subjects_strings)]
    return df
reset_pwd_df = retriving_subjects(filtered_df)
print("--------after secting on Please reset your password-----------------")
print(reset_pwd_df.shape)

(58100, 11)
----after removing bogus emails ------
(51510, 11)
------------------------

(51510, 11)
-------------------------

In [11]:
agg_obj_1 = filtered_df.groupby(['just_date', 'Subject'],as_index=False)
agg_df_1 = pd.DataFrame(agg_obj_1.agg({'Email Address' : 'nunique'}))
agg_df_1.rename(columns={'Email Address':'Unique Recipients'}, inplace=True)
print(agg_df_1.shape)
print(agg_df_1)
print()
agg_obj_2 = filtered_df.groupby(['just_date', 'Subject'],as_index=False)
agg_df_2 = pd.DataFrame(agg_obj_2.agg({'Email Address' : 'count'}))
agg_df_2.rename(columns={'Email Address':'Total Recipients'}, inplace=True)
print(agg_df_2.shape)
print(agg_df_2.head())
final_df = pd.merge(agg_df_1, agg_df_2, left_on=['just_date', 'Subject'], right_on=['just_date', 'Subject'], how='inner')
final_df

(651, 3)
     just_date                              Subject  Unique Recipients
0   2021-06-01                 Bem-vindo ao Skidos!                 56
1   2021-06-01                   Benvenuto a skidos                 15
2   2021-06-01                   Bienvenue à skidos                 23
3   2021-06-01             Forgotten your password?                 16
4   2021-06-01                       Glemt passord?                  1
..         ...                                  ...                ...
646 2021-07-01                [Skidos] New password                 23
647 2021-07-01                  [Skidos] Nova senha                  1
648 2021-07-01  [Skidos] Please reset your password                 20
649 2021-07-01          [Skidos] Redefina sua senha                  2
650 2021-07-01              ¡Bienvenido/a a SKIDOS!                 16

[651 rows x 3 columns]

(651, 3)
   just_date                   Subject  Total Recipients
0 2021-06-01      Bem-vindo ao Skidos!                56
1 2021-06-01        Benvenuto a skidos                15
2 2021-06-01        Bienvenue à skidos                23
3 2021-06-01  Forgotten your password?                34
4 2021-06-01            Glemt passord?                 2

,just_date,Subject,Unique Recipients,Total Recipients
0,2021-06-01,Bem-vindo ao Skidos!,56,56
1,2021-06-01,Benvenuto a skidos,15,15
2,2021-06-01,Bienvenue à skidos,23,23
3,2021-06-01,Forgotten your password?,16,34
4,2021-06-01,Glemt passord?,1,2
...,...,...,...,...
646,2021-07-01,[Skidos] New password,23,28
647,2021-07-01,[Skidos] Nova senha,1,1
648,2021-07-01,[Skidos] Please reset your password,20,32
649,2021-07-01,[Skidos] Redefina sua senha,2,3
650,2021-07-01,¡Bienvenido/a a SKIDOS!,16,16